---
# upstream
kafka_scala_version: "{{ kafka_versions[kafka_version]['scala_version'] }}"
kafka_archive_filename: "kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
kafka_download_base_url: "https://archive.apache.org/dist/kafka"
kafka_download_url: "{{ kafka_download_base_url }}/{{ kafka_version }}/{{ kafka_archive_filename }}"
kafka_dirname: "kafka_{{ kafka_scala_version }}-{{ kafka_versions[kafka_version]['microversion'] | regex_replace(' \\((.*)\\)$', '') }}"

# amqstreams
amqstreams_scala_version: "{{ amqstreams_versions[amqstreams_version]['scala_version'] }}"
amqstreams_archive_filename: "amq-streams-{{ amqstreams_version }}-bin.zip"
amqstreams_download_base_url: "https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html"
amqstreams_download_url: "{{ amqstreams_download_base_url }}?softwareId={{ amqstreams_versions[amqstreams_version]['rhn_id'] }}"
amqstreams_dirname: "kafka_{{ amqstreams_scala_version }}-{{ amqstreams_versions[amqstreams_version]['microversion'] | regex_replace(' \\((.*)\\)$', '') }}"

# upstream catalogue
kafka_versions:
  3.3.1:
    scala_version: 2.13
    microversion: 3.3.1 (Commit:e23c59d00e687ff5)
  3.2.3:
    scala_version: 2.13
    microversion: 3.2.3 (Commit:50029d3ed8ba576f)
  3.1.0:
    scala_version: 2.13
    microversion: 3.1.0 (Commit:37edeed0777bacb3)
  3.0.0:
    scala_version: 2.13
    microversion: 3.0.0 (Commit:8cb0a5e9d3441962)
  2.8.0:
    scala_version: 2.12
    microversion: 2.8.0 (Commit:ebb1d6e21cc92130)

# amqstreams catalogue
amqstreams_versions:
  2.3.0:
    scala_version: 2.13
    microversion: 3.3.1.redhat-00008 (Commit:da60911214b98021)
    rhn_id: 105011
  2.2.0:
    scala_version: 2.13
    microversion: 3.2.3.redhat-00003 (Commit:8c8f89d8e34196ab)
    rhn_id: 104745
  2.1.0:
    scala_version: 2.13
    microversion: 3.1.0.redhat-00004 (Commit:4c168d2882c7f93d)
    rhn_id: 104335
  2.0.1:
    scala_version: 2.13
    microversion: 3.0.0.redhat-00008 (Commit:a92f6b92b6cb42fe)
    rhn_id: 104108
  1.8.4:
    scala_version: 2.12
    microversion: 2.8.0.redhat-00004 (Commit:e4403b1af4b1e4d5)
    rhn_id: 103708
